### ISSUE TITLE
Windows fom Dock miniature view do not restore correctly

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-wm#28]
Hover over an application icon in the Dock, where several instances are running. Click on a minimized one. 
Mostly the window is not visible, but it is covering the desktop. If you guess right, you can even control the menu and stuff.

Very annyoing.

Running Deepin-Desktop on Arch with Multi-Monitor and therefore crashing deepin-desktop (known bug).

**Comment by sonald** [comment]
this has been fixed, and will be pushed later.

**Comment by DasJott** [comment]
Can't wait!

**Comment by DasJott** [comment]
Fix did not arrive yet. Is it not released or not really fixed?

**Comment by DasJott** [comment]
Still not fixed. And the Window decorations can not be disabled anymore.

**Comment by sonald** [comment]
@DasJott sorry, the fix has not been published yet. and what do you mean by `disable decoration`, and how do you do that?

**Comment by DasJott** [comment]
I would make a screenshot, but that's not possible as it is in the settings bar.
Under Customization there are Window effects (not decoration, sorry) on and off switchable. Usually to get a window restored on this bug occuring, you could switch those effects off to get it back. Otherwise you could only close it.

Any idea when it will be published?

**Comment by sonald** [comment]
@DasJott if you use any of arch based distribution, it'll be soon. 
about the `window effects` switch problem, you can report an issue here https://github.com/linuxdeepin/developer-center/issues, the team will handle it.

**Comment by DasJott** [comment]
There was a huge update with lots of improvements yesterday. Sadly this one was not solved.
See here, that the window is kinda restored, but not visible. Menu is still usable if you know, where it is.
![restoreerror](https://user-images.githubusercontent.com/6298761/37453953-91b79292-2839-11e8-9f79-66ab80b5c7f5.png)

**Comment by sonald** [comment]
@DasJott what is the version of deepin-wm ?

**Comment by DasJott** [comment]
Funny story. Executing `deepin-wm --version` gives me this: `Gala unknown`.
Does that help?

**Comment by sonald** [comment]
@DasJott my mistake. I confused this with another similar problem I have fixed. this has just been fixed, and will update soon.

**Comment by DasJott** [comment]
Today after a reboot I noticed, that the bug is back!
So one of the last few updates must have broken it again. :(

**Comment by sonald** [comment]
@DasJott Can not reproduce that. plz try deepin-wm 1.9.29 released today.
